module.exports = [
    'Kelurahan',
    'Antang',
    'Baji Mappakasunggu',
    'Bakung',
    'Balla Parang',
    'Bangkala',
    'Banta - Bantaeng',
    'Bara - Baraya Selatan',
    'Bara - Baraya Timur',
    'Bara - Baraya Utara',
    'Barana',
    'Baraya',
    'Barombong',
    'Barrang Caddi',
    'Barrang Lompo',
    'Baru',
    'Batua',
    'Berua',
    'Bira',
    'Biring Romang',
    'Bitowa',
    'Bongaya',
    'Bonto Biraeng',
    'Bonto Duri',
    'Bonto Lebang',
    'Bonto Makkio',
    'Bontoala',
    'Bontoala Parang',
    'Bontoala Tua',
    'Bontorannu',
    'Borong',
    'Bua Kana',
    'Buloa',
    'Bulogading',
    'Bulurokeng',
    'Bunga Eja Beru',
    'Bunga Ejaya',
    'Buntusu',
    'Butung',
    'Cambaya',
    'Daya',
    'Ende',
    'Gaddong',
    'Gunung Sari',
    'Gusung',
    'Jongaya',
    'Kaluku Bodoa',
    'Kalukuang',
    'Kampung Buyang',
    'Kapasa',
    'Kapasa Raya',
    'Karampuang',
    'Karang Anyar',
    'Karunrung',
    'Karuwisi',
    'Karuwisi Utara',
    'Kassi - Kassi',
    'Katimbang',
    'Kodingareng',
    'Bara - Baraya',
    'Kunjung Mae',
    'Labuang Baji',
    'Lae - Lae',
    'Laikang',
    'Lajangiru',
    'Lakkang',
    "La'latang",
    'Lariang Bangi',
    'Layang',
    'Lembo',
    'Lette',
    'Losari',
    'Maccini',
    'Maccini Gusung',
    'Maccini Parang',
    'Maccini Sombala',
    'Malimongan',
    'Malimongan Baru',
    'Malimongan Tua',
    'Maloku',
    'Mamajang Dalam',
    'Mamajang Luar',
    'Mampu',
    'Mandala',
    'Mangasa',
    'Manggala',
    'Mangkura',
    'Mannuruki',
    'Mapala',
    'Maradekaya',
    'Maradekaya Selatan',
    'Maradekaya Utara',
    'Maricaya',
    'Maricaya Baru',
    'Maricaya Selatan',
    'Mario',
    'Mariso',
    'Masale',
    'Mattoangin',
    'Melayu',
    'Melayu Baru',
    'Minasa Upa',
    "Pa'baeng - Baeng",
    "Pa'batang",
    'Paccerakkang',
    'Pai',
    'Pampang',
    'Panaikang',
    'Panambungan',
    'Pandang',
    'Pannampu',
    'Parang',
    'Parang Layang',
    'Parang Loe',
    'Parang Tambung',
    'Paropo',
    'Pattingalloang',
    'Pattingalloang Baru',
    'Pattunuang',
    'Pisang Selatan',
    'Pisang Utara',
    'Rappocini',
    'Rappojawa',
    'Rappokalling',
    'Sambung Jawa',
    'Sawerigading',
    'Camba Berua',
    'Sinrijala',
    'Suangga',
    'Sudiang',
    'Sudiang Raya',
    'Tabaringan',
    'Tallo',
    'Tamalabba',
    'Tamalanrea',
    'Tamalanrea Indah',
    'Tamalanrea Jaya',
    'Balang Baru',
    'Tamamaung',
    'Tamangapa',
    'Tamarunang',
    'Tammua',
    'Tamparang Keke',
    'Tanjung Merdeka',
    'Tello Baru',
    'Tidung',
    'Timungan Lompoa',
    'Tompo Balang',
    'Totaka',
    'Ujung Pandang Baru',
    'Ujung Tanah',
    'Untia',
    'Wajo Baru',
    'Wala - Walaya',
];